//
// Created by Walid on 5/3/2017.
//

#ifndef SIC_ASSEMBLER_INTERMEDIATEFILEWRITER_H
#define SIC_ASSEMBLER_INTERMEDIATEFILEWRITER_H


class IntermediateFileWriter {

};


#endif //SIC_ASSEMBLER_INTERMEDIATEFILEWRITER_H
